---
- hosts: webservers
  become: yes
  become_user: root
  tasks:
  - name: Installing Latest version of Apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: Restart service httpd, in all cases
    service:
       name: apache2
       enabled: yes
       state: started
  - name: Remove eixisting index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: Create a new empty index.html
    file:
      path: /var/www/html/index.html
      state: touch
      owner: root
      group: root
      mode: 0755
  - name: add content to index.html file
    lineinfile:
      path: /var/www/html/index.html
      line: Hello Participants, Ansible World !
