---
- name: Test the website
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Check port 80 is listening to managed nodes
    wait_for:
      port: 80
      state: started
      timeout: 3

  - name: Verify Apache is available remotely
    uri:
      url: http://{{ ansible_host }}/index.html
    delegate_to: localhost

  - name: Stat apache2
    stat:
      path: /usr/sbin/apache2
    register: i

  - name: Fail if apache2 doesnt exists
    assert:
      that:
       - "i.stat.exists"
      fail_msg: "/usr/sbin/apache2 doesnt exists"
      success_msg: "/usr/sbin/apache2 is enabled"

  - name: Stat index.html
    stat:
      path: /var/www/html/index.html
    register: a

  - name: Confirm that index.html exists and owned by root
    assert:
      that:
       - "a.stat.exists"
       - "a.stat.pw_name == 'root'"
      fail_msg: "index.html may doesnt exists or not owned by root"
      success_msg: "index.html exists with proper ownership"
