version: 2.1

orbs:  
  ansible: hux/ansible@0.1.6
  slack: circleci/slack@4.2.0
jobs:
  run-ansible:
    working_directory: /tmp/ansible
    machine: true
    steps:
    - add_ssh_keys:
          fingerprints:
            - "b6:6c:11:1f:a3:ee:dd:a4:e3:d6:0e:99:e8:fe:ba:b9"
    - checkout
    - run:
        name: Deploy Ansible via control node
        command: |
          scp -r ./ ubuntu@18.191.26.248:~/
          ls -la
          ssh ubuntu@18.191.26.248 "ansible-playbook ./playbooks/website-update.yml"
    - run:
        name: Validation of deployed Apache Server
        command: |
          curl http://3.16.206.77/index.html
    - slack/notify:
        event: fail
        mentions: "<@elon>"
        template: basic_fail_1
    - slack/notify:
        event: pass        
        template: success_tagged_deploy_1
  run-intergration-tests:
    machine: true
    steps:
    - add_ssh_keys:
          fingerprints:
            - "b6:6c:11:1f:a3:ee:dd:a4:e3:d6:0e:99:e8:fe:ba:b9"
    - checkout
    - run:
        name: Execute test cases via control node
        command: |
          scp ./playbooks/*.yml ubuntu@18.191.26.248:~/
          ssh ubuntu@18.191.26.248 "ansible-playbook website-test.yml"
    - slack/notify:
        event: fail
        mentions: "<@elon>"
        template: basic_fail_1
    - slack/notify:
        event: pass
        template: success_tagged_deploy_1        
workflows:
  ansible-using-orbs:
    jobs:
      - ansible/ansible-lint:
          config: ./lint-config/lint-config.yml
      - slack/on-hold:
          context: slack-secrets
          mentions: "@elon"
          requires:
            - ansible/ansible-lint
      - pause_for_approval:
          requires:
            - slack/on-hold
          type: approval
      - ansible/ansible-playbook-syntax:
          dir: ./playbooks
          depth: 1
          requires:
            - pause_for_approval            
      - run-ansible:
          requires:
            - ansible/ansible-playbook-syntax
          context: slack-secrets
      - run-intergration-tests:
          requires:            
            - run-ansible
          context: slack-secrets
