version: 2.1

orbs:  
  ansible: hux/ansible@0.1.6
  slack: circleci/slack@4.2.0

workflows:
  ansible-using-orbs:
    jobs:
      - ansible/ansible-lint:
          config: ./lint-config/lint-config.yml
      - slack/on-hold:
          context: slack-secrets
          mentions: "@elon"
          requires:
            - ansible-lint
      - pause_for_approval:
          requires:
            - ansible/ansible-lint
            - slack/on-hold
          type: approval
      - ansible/ansible-playbook-syntax:
          dir: .
          depth: 1
          requires:
            - pause_for_approval
            - ansible/ansible-lint
            