version: 2.1

orbs:  
  ansible: hux/ansible@0.1.6  

workflows:
  ansible-using-orbs:
    jobs:
      - ansible/ansible-lint:
          config: ./lint-config/lint-config.yml
      - ansible/ansible-playbook-syntax:
          dir: .
          depth: 1
        